### ISSUE TITLE
how can i make this to use for multiple users? 

### ISSUE THREAD

**Issue by ishanShahzad** [emad-elsaid/restreamer#1]
Hi @emad-elsaid ,
I want to use this restreamer for multiple users. can you help me with this?

**Comment by emad-elsaid** [comment]
This image was written with one user in mind, if you want to use it for multiple users that approach I took in this image won't work you'll have to rethink it from the beginning

**Comment by ishanShahzad** [comment]
currently, i am executing a runtime container for every user who wants to stream. so there is one container for every user. how can I do this in one container? can you give me any hint or reference? any hint on how **restream.io** is doing that?
